# Generated by Django 2.1 on 2018-09-16 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='需求名称')),
                ('publish_date', models.DateField(auto_now_add=True, verbose_name='需求日期')),
                ('priority', models.IntegerField(default='4', verbose_name='优先级')),
                ('percent', models.IntegerField(blank=True, verbose_name='进度')),
                ('status', models.CharField(choices=[('unknow', '未知'), ('undone', '未完成'), ('done', '完成')], max_length=10, verbose_name='状态')),
            ],
            options={
                'verbose_name': '需求',
                'verbose_name_plural': '需求',
            },
        ),
        migrations.CreateModel(
            name='human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='公司')),
                ('deparment', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='职务')),
                ('human_type', models.CharField(blank=True, choices=[('untyped', '未分类'), ('publisher', '需求方'), ('processor', '承接方')], default='未分类', max_length=100, verbose_name='身份类型')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话号码')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': '参与人',
                'verbose_name_plural': '参与人',
            },
        ),
        migrations.AddField(
            model_name='demand',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='承接人', to='demand.human'),
        ),
        migrations.AddField(
            model_name='demand',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='需求人', to='demand.human'),
        ),
    ]
