# Generated by Django 2.1 on 2018-09-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='human_type',
            field=models.CharField(blank=True, choices=[('untyped', '未分类'), ('publisher', '需求方'), ('processor', '承接方')], default='未分类', max_length=100, verbose_name='身份类型'),
        ),
    ]
