# Generated by Django 2.1 on 2018-09-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('priority', models.IntegerField(default='4')),
                ('percent', models.IntegerField(blank=True)),
            ],
        ),
    ]
