# Generated by Django 2.1 on 2018-09-16 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0002_demand_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='demand_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='状态名称')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='描述')),
            ],
            options={
                'verbose_name': '需求状态',
                'verbose_name_plural': '需求状态',
            },
        ),
        migrations.AlterField(
            model_name='demand',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='需求', to='demand.demand_status'),
        ),
    ]
