# Generated by Django 2.1 on 2018-09-16 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0003_auto_20180916_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand_status',
            name='color_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='颜色代码'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='承接人', to='demand.human', verbose_name='承接人'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='需求人', to='demand.human', verbose_name='需求人'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='需求', to='demand.demand_status', verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='human',
            name='human_type',
            field=models.CharField(blank=True, choices=[('untyped', '未分类'), ('publisher', '需求方'), ('processor', '承接方')], default='未分类', max_length=100, verbose_name='类型'),
        ),
    ]
