# Generated by Django 2.1 on 2018-09-17 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0006_auto_20180916_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='human',
            old_name='human_type',
            new_name='humantype',
        ),
    ]
