# Generated by Django 2.1 on 2018-09-23 03:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0008_auto_20180923_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='ask_end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='要求完成日期'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='plan_begin_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='计划开发日期'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='plan_end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='计划完成日期'),
        ),
    ]
