# Generated by Django 2.1 on 2018-09-23 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0010_auto_20180923_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demand.priority', verbose_name='优先级'),
        ),
    ]
