# Generated by Django 2.1 on 2018-09-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0011_auto_20180923_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='ask_end_date',
            field=models.DateField(blank=True, verbose_name='要求完成日期'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='plan_begin_date',
            field=models.DateField(blank=True, verbose_name='计划开发日期'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='plan_end_date',
            field=models.DateField(blank=True, verbose_name='计划完成日期'),
        ),
    ]
