# Generated by Django 2.1 on 2018-09-24 01:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0012_auto_20180923_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='ask_end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='要求完成日期'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='firster',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='甲方对接人', to='demand.human', verbose_name='甲方对接人'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='need_auto',
            field=models.BooleanField(default=True, verbose_name='固化'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='plan_begin_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='计划开发日期'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='plan_end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='计划完成日期'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='processor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='承接人', to='demand.human', verbose_name='承接人'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='publisher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='需求人', to='demand.human', verbose_name='需求人'),
        ),
    ]
