# Generated by Django 2.1 on 2018-09-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0014_demand_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand_step',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='需求名称'),
        ),
    ]
