# Generated by Django 2.1 on 2018-09-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='color_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='颜色名称')),
                ('color_code', models.CharField(blank=True, max_length=10, verbose_name='颜色代码')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='描述')),
            ],
            options={
                'verbose_name': '颜色代码',
                'verbose_name_plural': '颜色代码',
            },
        ),
    ]
